// <auto-generated />
using MVCData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCData.Migrations
{
    [DbContext(typeof(MVCEFDbContext))]
    [Migration("20211203093522_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCData.Data.MLink", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LinkURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Name");

                    b.ToTable("MLinks");

                    b.HasData(
                        new
                        {
                            Name = "AJAX",
                            LinkURL = "/Ajax/Index",
                            Title = "AJAX"
                        });
                });

            modelBuilder.Entity("MVCData.Data.PersonDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Göteborg",
                            Name = "Mahnoush",
                            PhoneNumber = "0738090123"
                        },
                        new
                        {
                            ID = 2,
                            City = "Stockholm",
                            Name = "Donja",
                            PhoneNumber = "0748090124"
                        },
                        new
                        {
                            ID = 3,
                            City = "Ystad",
                            Name = "Awa",
                            PhoneNumber = "0758090125"
                        },
                        new
                        {
                            ID = 4,
                            City = "Malmö",
                            Name = "Diana",
                            PhoneNumber = "0768090126"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
